export enum SystemModuleKey {
  CADASTRO = 'CADASTROS',
  CADASTRO_USUARIO = 'CADASTRO_USUARIO',
  CADASTRO_PESSOA = 'CADASTRO_PESSOA',
  CADASTRO_UNIDADE_NEGOCIO = 'CADASTRO_UNIDADE_NEGOCIO',
  CADASTRO_PERFIL = 'CADASTRO_PERFIL',
  FINANCEIRO = 'FINANCEIRO',
  FINANCEIRO_PLANO_CONTAS = 'FINANCEIRO_PLANO_CONTAS',
  FINANCEIRO_CONTA_BANCARIA = 'FINANCEIRO_CONTA_BANCARIA',
  FINANCEIRO_TITULO_CATEGORIA = 'FINANCEIRO_TITULO_CATEGORIA',
  FINANCEIRO_TITULO = 'FINANCEIRO_TITULO',
  FINANCEIRO_MOVIMENTACAO_FINANCEIRA = 'FINANCEIRO_MOVIMENTACAO_FINANCEIRA',
  FINANCEIRO_CENTRO_CUSTO = 'FINANCEIRO_CENTRO_CUSTO',
}
