package br.com.grupopipa.gestaointegrada.core.enums;

import lombok.Getter;

@Getter
public enum SystemModuleKey {
    CADASTRO("CADASTRO"),
    CADASTRO_USUARIO("CADASTRO_USUARIO"),
    CADASTRO_PESSOA("CADASTRO_PESSOA"),
    CADASTRO_UNIDADE_NEGOCIO("CADASTRO_UNIDADE_NEGOCIO"),
    CADASTRO_PERFIL("CADASTRO_PERFIL"),
    FINANCEIRO("FINANCEIRO"),
    FINANCEIRO_PLANO_CONTAS("FINANCEIRO_PLANO_CONTAS"),
    FINANCEIRO_CONTA_BANCARIA("FINANCEIRO_CONTA_BANCARIA"),
    FINANCEIRO_CATEGORIA_TITULO("FINANCEIRO_CATEGORIA_TITULO"),
    FINANCEIRO_TITULO("FINANCEIRO_TITULO"),
    FINANCEIRO_MOVIMENTACAO_FINANCEIRA("FINANCEIRO_MOVIMENTACAO_FINANCEIRA"),

    ATENDIMENTO_PROFISSIONAL("ATENDIMENTO_PROFISSIONAL");

    private final String key;

    SystemModuleKey(String key) {
        this.key = key;
    }
}
